### ISSUE TITLE
下掉 iOS 崩溃报告指南

### ISSUE THREAD

**Issue by nicecui** [leancloud/docs#2360] opened 2017-11-01 09:21 UTC
https://leancloud.cn/docs/ios_crashreporting_guide.html

![image](https://user-images.githubusercontent.com/10130959/32268156-dc4fc776-bebb-11e7-827e-73a1266f2074.png)

![image](https://user-images.githubusercontent.com/10130959/32268199-0c5f25ba-bebc-11e7-9f08-6f7a486eff32.png)

**Comment by myleslee** [comment] 2017-11-01 10:33
dupe of #2352
closed by #2354 
changes not in effectivity because docs wasn't rebuilt just yet

**Closed by myleslee** 2017-11-01 10:33 UTC
